---
title: "Specialization decreases with increasing resource availability in a tropical plant-pollinator network."
author: "Ben Weinstein"
date: "Tuesday, October 14, 2014"
output:
  html_document:
    theme: spacelab
---

```{r,echo=FALSE,warning=FALSE,message=FALSE}
require(knitr)
require(reshape2)
require(ggplot2)
library(scales)
opts_chunk$set(message=FALSE,warning=FALSE,fig.width=10,echo=FALSE)
```

#Introduction
* Species interactions are under growing threat from climate change.

* The stability of biotic interactions depends on their relative specialization and generality.

* In this work we define specialization as the number of food plants used by a hummingbird species.

* While many plant-pollinator networks show a pattern of nestedness, with generalist pollinators using specialized resources, these networks tend to be analyzed as single static landscapes.

    * In reality, biotic interactions occur against a shifting background of resource availability.

* We divide the plant-pollinator assemblage into temporal partitions to evaluate how co-occuring plants and pollinators partition resource space.

* We present two competiting hypothesis for the relationship between specialization, available resources and trait matching.

###Specialization should increase as available resources increases

At times of low resource availablity species cannot be choosy, and must forgage on whatever plants are available. Species should prefer to partition resource space when possible, as to reduced competition among species. This niche partitioning mechanism is central to many explanations of the latitudinal gradient in species diversity, i.e that greater resources lead to finer subdivision of niche space, and promotes reproductive isolation.

###Specialization should decrease as available resources increases

When there are an abundance of available resources, species do not suffer as much cost from competition. The plethora of option leads to decreased specialization as species maximize amount of time feeding and reduced time foraging for their specialized resource.
The observation that many morphological specialists forage as generalists during periods of high resource availability led to Liem’s Paradox in Cichlids. Sloan-Wilson () suggested that the solution to this paradox is that the specialists fall back on private resources in time of low scarcity, which promotes greater morphological specialization.

####Trait-Matching and Specialization

The above hypothesis predict a pattern of specialization and resources, but provide no direct mechanism by which hummingbirds choose which resource for specialization. It has been repeated suggested that hummingbird foodplant specialization is mediated through bill-corolla phenotype matching. We therefore expect that as specialization increase, the strength of phenotypic matching should decrease. When given a choice, species should pick the flowers which reduce competition and closely match their bill morphology.

#Methods
#Results

#Discussion